const cat = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_kTyp-KFqe'
const bg = 'https://ik.imagekit.io/euurqxbuc/uploaded-asset_EcxR9eWy0'
const textContent =
  "THIS YEAR, CREO 26' IS THE FIRST EDITION OF NIT ROURKELA’S NATIONAL DESIGN CONFERENCE, CURATED TO EXPLORE HOW DESIGN DRIVES INNOVATION BEYOND AESTHETICS. THE CONFERENCE FOCUSES ON PRODUCT THINKING, HUMAN CENTERED DESIGN, SUSTAINABILITY, CREATIVE TECHNOLOGY, AND DESIGN LED ENTREPRENEURSHIP. THROUGH TALKS, WORKSHOPS, DESIGNATHON, AND EXHIBITIONS, CREO 26' CONNECTS STUDENTS."

export { cat, bg, textContent }
